### ISSUE TITLE
Missing path

### ISSUE THREAD

**Issue by mearno** [lukaskleinschmidt/kirby-sortable#10]
Hi,

I've set up a clean kirby, installed the modules plugin, which works fine as far as could see.

Than I installed the modules field:
- adding/creating modules works fine
- modules are created in content/page/modules subdirectory
- modules are there but it shows 'no modules yet'

For the field in panel I get this:

![schermafbeelding 2016-09-09 om 11 21 28](https://cloud.githubusercontent.com/assets/2323826/18382166/1d1b357c-7680-11e6-92b4-c86b7873582f.png)

Do you have any idea?

Thanks,
Arno

**Comment by lukaskleinschmidt** [comment]
Please see the last release. There was an issue with the latest changes in the modules-plugin.

**Comment by mearno** [comment]
Yes, that fixed it, I downloaded yesterday so it was fresh but not fresh enough :)

Thanks!

**Comment by lukaskleinschmidt** [comment]
Actually i just fixed it ;)
Have to keep an eye on the plugin.
