### ISSUE TITLE
Class 'PermissionsException' not found

### ISSUE THREAD

**Issue by movingwater** [lukaskleinschmidt/kirby-sortable#15]
If I want to delete a module with the delete button I get the error: 
> Class 'PermissionsException' not found

it gives me the following debug infos:
`.../site/plugins/modules-field/fields/modules/controller.php`
on line 64 - 66
```
if($page->ui()->delete() === false) {
  throw new PermissionsException();
}
```

I'm on Kirby 2.4.0.

**Comment by lukaskleinschmidt** [comment]
Yeah i forgot to set the namespace for PermissionException. But that would only fix the exception. You would still not be allowed to delete pages. Is it intendet that you are not able to do so?

**Comment by movingwater** [comment]
I'm not sure if I understand you correct. But my goal would be, that I CAN delete the modules. Or how can I set it up to delete this pages?

**Comment by lukaskleinschmidt** [comment]
It is a error from the plugin that the class is not available. I added a fix for that a minute ago.
But the PermissionException class gets called only when you don't have the permission to delete a page in the first place.

So the fix probably just changes the thrown exception right now.

Do you have any permissions set up to prevent page deletion?

**Comment by movingwater** [comment]
Somehow it seems I don't have the permissions. But I don't know why. I don't have set any limitations in deleting pages. Normal subpages are deletable. But I'm not able to delete modules. Do I have to actively set modules as deletable? If yes, how?

**Comment by lukaskleinschmidt** [comment]
Thats odd. Is the default delete Button on the left available when you are in the edit view of a module?

**Comment by movingwater** [comment]
No, unfortunately not. Maybe I'll try to set up a fresh version of kirby...

**Comment by movingwater** [comment]
Just found the problem: It's a conflict with the revisions plugin. As soon as I dectivate the revisions plugin the deletion of modules works as expected.

**Comment by lukaskleinschmidt** [comment]
Good to know.
Hopfully jens can sort this out quick.
