### ISSUE TITLE
Multilang title for modules not working like expected

### ISSUE THREAD

**Issue by ralfgoeke** [lukaskleinschmidt/kirby-sortable#17]
If I use translation strings inside yaml (site/modules/mymodule.yml), like so:

```
title:
  de: Mein Modul
  en: My Module
```

in the module overview it prints out the generic module name rather than the correct language string.

I accidentally opened this issue over at the kirby-modules repo first, so if it's a problem with the modules plugin, here's the link to the issue: https://github.com/getkirby-plugins/modules-plugin/issues/12

**Comment by lukaskleinschmidt** [comment]
I will have a look at this tomorrw

**Comment by lukaskleinschmidt** [comment]
If you find any further issues or missiing features regarding a multilanguage setup please let me know.
