### ISSUE TITLE
Hide subpage containing modules

### ISSUE THREAD

**Issue by l4ci** [lukaskleinschmidt/kirby-sortable#2]
I setup the modules plugin, so that they are in a subpage with the UID `modules` and not direct children of the parent page (as you recommended [here](https://github.com/getkirby-plugins/modules-plugin#creating-modular-content-in-the-panel)).

So with this fields module installed, is there a way to completely hide the `modules` folder form the subpages and only show real ones?

**Comment by lukaskleinschmidt** [comment]
You can simply set `hide: true` in the modules page blueprint.

**Comment by SirNovi** [comment]
I'm wondering if I made a mistake somewhere on the way or how else this question didn't come up yet: If I hide the modules folder in the panel, then it can't be reached via the panel anymore and it can't be deleted either. Which leads to the issue that the real page itself can't be deleted via the panel anymore. 

Did I do something wrong or is that only an issue for me?

**Comment by lukaskleinschmidt** [comment]
That is a pain point for me too but that is something that the kirby should fix. I think it is on their 2.5 roadmap.

To get the option right now you could write a plugin that adds the delete link to the sidebar with a custom route where you can delete the page with the `$force = true` parameter.
