### ISSUE TITLE
Inconsistant plugin name

### ISSUE THREAD

**Issue by jenstornell** [lukaskleinschmidt/kirby-sortable#24]
The repo is called `kirby-field-modules` and the folder when downloaded is like `kirby-field-modules-master`.

But the plugin folder should be renamed `modules-field`. Maybe match the repo with the plugin name or the other way around.

(nice field by the way)

**Comment by lukaskleinschmidt** [comment]
That is still a relict from the time this plugin was a field.

I was planning to rename it `kirby-modules-field`. But then you still have to change the folder name. With this in mind I decided to keep the name and don't mess with the remote url of this repo.

Perhaps I could make it more clear in the readme.

**Comment by jenstornell** [comment]
Or the other way around. Rename it and then add a big notice about it in the readme?

**Comment by olach** [comment]
It should be no problem renaming the repo. GitHub has automatic redirects when renaming repos. https://github.com/blog/1508-repository-redirects-are-here

**Comment by lukaskleinschmidt** [comment]
Did not know that. Thanks for the reference. I will rename the repo then.
