### ISSUE TITLE
Error 500 on update if status:false in child's blueprint 

### ISSUE THREAD

**Issue by SamuelRiversMoore** [lukaskleinschmidt/kirby-sortable#36]
Hi, 

I have an error returned each time the field is updated.
After investigation it looks like the error is caused by the fact that `status` option is set to `false` in the child's blueprint. 
Maybe would it be nice to add a warning or so?
Cheers :-)

**Comment by lukaskleinschmidt** [comment]
I will have a closer look at this.

**Comment by lukaskleinschmidt** [comment]
There is now an option to disable sorting completely.
https://github.com/lukaskleinschmidt/kirby-sortable#sortable-1
