### ISSUE TITLE
Copy Page / recursively endless spinn

### ISSUE THREAD

**Issue by H-i-red** [lukaskleinschmidt/kirby-sortable#38]
Hi,
If I copy A page and paste that page inside the page that i copied, it creates a recursively endless spinn, and creates endless subpages.

Is this a Bug or how do I prevent this from happening !?
Of Course it works if I copy another and paste that page inside the page.

**Comment by lukaskleinschmidt** [comment]
Thats actually a nasty bug. But it is something that should be fixed in the toolkit core.
If for some reason this will not get fixed in the core I will implement a workaround.

**Comment by H-i-red** [comment]
AWESOME YOUR FIX WORKS !

**Comment by lukaskleinschmidt** [comment]
This one is now fixed in the [latest Kirby](https://getkirby.com/changelog/kirby-2-5-7) release.
