### ISSUE TITLE
Role based actions in layouts

### ISSUE THREAD

**Issue by georgobermayr** [lukaskleinschmidt/kirby-sortable#44]
Hi,

is it possible to to access the current role of the panel user in a custom layout?
`$this` only contains Page and Field data and the other default Kirby variables also don't work.
For instance I want to hide toggle or delete buttons if the current user is not in the admin role.
Is there any way to achieve this?

Kind regards,
Georg

**Comment by lukaskleinschmidt** [comment]
You should be able to get the current user with `site()->user()`.

**Comment by georgobermayr** [comment]
Indeed. Thank you!
