### ISSUE TITLE
Drag and Drop not working in IE 11

### ISSUE THREAD

**Issue by georgobermayr** [lukaskleinschmidt/kirby-sortable#45]
Hi,

drag and drop of sortable elements seems not to work with IE 11. The mouse icon changes but the elements are not dragable. 
Do you have any idea?

Kind regards,
Georg

**Comment by lukaskleinschmidt** [comment]
It is working fine for me on Windows 10 and 7. Do you get any errors in the console?

**Comment by georgobermayr** [comment]
You are right, sorry for opening the issue. There was an issue with another plugin, Kirby SimpleMDE, that is not working in IE 11 and causing JS errors. This broke drag & drop in Sortable.
I openend an issue here: https://github.com/medienbaecker/kirby-simplemde/issues/17
