### ISSUE TITLE
in the add modal are modules and page templates shown mixed

### ISSUE THREAD

**Issue by laleikeCO** [lukaskleinschmidt/kirby-sortable#50]
I've a page where i use some modules and have also the possibility to add subpages. So when I want create a new module the add modal shows me the subpage templates as well. Don't know if it's a bug or a feature, but for my case it would be better if I only have the module templates there.

For me a workaround helps me quite well, I'd edit the site/plugins/sortable/sortable/actions/add/forms/add.php that only modules with prefix are shown.

`
foreach($page->blueprint()->pages()->template()->filterBy('name', '*=', $field->prefix()) as $template) {
    $options[$template->name()] = $template->title();
 }
`

**Comment by lukaskleinschmidt** [comment]
Filtering available tempaltes by the prefix is a good addition and probably the expected behaviour anyway.

I'm open for a PR on this one @laleikeCO.
