### ISSUE TITLE
PHP 7.4.x and Kirby 2.5.13

### ISSUE THREAD

**Issue by findthebug** [lukaskleinschmidt/kirby-sortable#52]
We have to update your k2 installation because of php upgrade. is the sortable/modules plugin compatible with the latest kirby 2.5.13 patch and php 7.4.x?

**Comment by lukaskleinschmidt** [comment]
I did a quick test and there was a bug with `strpos` and `null` as a needle. I fixed it on the master branch. Did you run into anything else @findthebug?

**Comment by findthebug** [comment]
we did some testing and have no issues with php7.4 and 2.5.13 kirby/panel. its it possible to publish a new release?

**Comment by findthebug** [comment]
okay, i took the master. looks like all is working. but maybe a new release would be great, also other user can download without checking this issue. thanks man!

**Comment by lukaskleinschmidt** [comment]
I just published a new release
https://github.com/lukaskleinschmidt/kirby-sortable/releases/tag/v2.4.2
