### ISSUE TITLE
Is the modules-plugin required?

### ISSUE THREAD

**Issue by digiltd** [lukaskleinschmidt/kirby-sortable#9]
In the readme it states  "This field is build on top of Kirby Modules Plugin."

Does that mean the original plugin (https://github.com/getkirby-plugins/modules-plugin) is not required? 

Or is this field more of an extension of the original plugin?

**Comment by lukaskleinschmidt** [comment]
The original [Kirby Modules Plugin](https://github.com/getkirby-plugins/modules-plugin) is required.
This field is like a UI for the plugin.

**Comment by digiltd** [comment]
Thanks
